defaults:
  - dataset: partnet_mobility
  - task: open_cabinet
  - pose_estimator: ground_truth
  - manipulation: open_cabinet
  - controller: heuristic_pose
  - train: default
  - _self_

exp_name: test
headless: False
viewerless: False # no cameras activated